### ISSUE TITLE
pass on warc.gz error

### ISSUE THREAD

**Issue by marked** [chfoo/warcat#20]
I'm not sure if this is suppose to be supported but this generates an error.

$ python3 -m warcat pass co012304aa.warc.gz
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/marked/.local/lib/python3.7/site-packages/warcat/__main__.py", line 154, in <module>
    main()
  File "/home/marked/.local/lib/python3.7/site-packages/warcat/__main__.py", line 70, in main
    command_info[1](args)
  File "/home/marked/.local/lib/python3.7/site-packages/warcat/__main__.py", line 113, in pass_command
    warc.load(filename, force_gzip=args.force_read_gzip)
TypeError: load() got an unexpected keyword argument 'force_gzip'

**Comment by acrois** [comment]
@marked I submitted a PR to address the issue based on "develop" branch. Let me know if I can be of any help @chfoo
